"""Vocabulário do Public Procurement (§38-§48)."""

from app.contexts.procurement import fluxo

STATUS_DEMANDA = ("RASCUNHO", "ENVIADA", "EM_ANALISE", "APROVADA", "REJEITADA", "CONSOLIDADA", "ATENDIDA")
STATUS_PLANO = ("ELABORACAO", "APROVADO", "PUBLICADO", "EM_EXECUCAO", "ENCERRADO")
STATUS_ITEM_PCA = ("PLANEJADO", "EM_PROCESSO", "CONTRATADO", "CANCELADO")
# Ciclo do §38 (processo): vem do workflow declarativo (S4), `fluxo.py` é a fonte única.
STATUS_PROCESSO = fluxo.PROCESSO.estados
STATUS_PROCESSO_FINAIS = fluxo.PROCESSO.finais
TIPOS_EVENTO_PROCESSO = ("APROVACAO", "ESCLARECIMENTO", "TAREFA", "MARCO", "NOTA")
STATUS_CONTRATO = ("VIGENTE", "SUSPENSO", "ENCERRADO", "RESCINDIDO")
TIPOS_EVENTO_CONTRATO = ("ADITIVO", "ENTREGA", "FISCALIZACAO", "PAGAMENTO", "OCORRENCIA", "RENOVACAO", "ENCERRAMENTO")
TIPOS_DOCUMENTO = (
    "ETP", "TR", "EDITAL", "CONTRATO", "ADITIVO", "ATA", "PESQUISA_PRECO", "PARECER", "RELATORIO", "DOC_FORNECEDOR", "OUTRO",
)
FONTES_PRECO = ("PAINEL_PRECOS", "CONTRATACAO_SIMILAR", "COTACAO_FORNECEDOR", "SITE", "OUTRO")
CLASSIFICACOES = ("PUBLIC", "INTERNAL", "CONFIDENTIAL", "RESTRICTED")
# Documento que o processo deveria ter a partir de cada etapa: regra do ruleset (S4).
DOCUMENTOS_ESPERADOS = fluxo.LEI_14133.documentos_esperados
