"""Vocabulário do Public Procurement (§38-§48)."""

STATUS_DEMANDA = ("RASCUNHO", "ENVIADA", "EM_ANALISE", "APROVADA", "REJEITADA", "CONSOLIDADA", "ATENDIDA")
STATUS_PLANO = ("ELABORACAO", "APROVADO", "PUBLICADO", "EM_EXECUCAO", "ENCERRADO")
STATUS_ITEM_PCA = ("PLANEJADO", "EM_PROCESSO", "CONTRATADO", "CANCELADO")
# Ciclo do §38 (processo), parametrizável por órgão no futuro.
STATUS_PROCESSO = (
    "PLANEJAMENTO", "ESTUDOS_TECNICOS", "TERMO_REFERENCIA", "PESQUISA_PRECOS", "APROVACAO", "PUBLICADO",
    "SELECAO", "HOMOLOGADO", "CONTRATADO", "FRACASSADO", "CANCELADO",
)
STATUS_PROCESSO_FINAIS = ("CONTRATADO", "FRACASSADO", "CANCELADO")
TIPOS_EVENTO_PROCESSO = ("APROVACAO", "ESCLARECIMENTO", "TAREFA", "MARCO", "NOTA")
STATUS_CONTRATO = ("VIGENTE", "SUSPENSO", "ENCERRADO", "RESCINDIDO")
TIPOS_EVENTO_CONTRATO = ("ADITIVO", "ENTREGA", "FISCALIZACAO", "PAGAMENTO", "OCORRENCIA", "RENOVACAO", "ENCERRAMENTO")
TIPOS_DOCUMENTO = (
    "ETP", "TR", "EDITAL", "CONTRATO", "ADITIVO", "ATA", "PESQUISA_PRECO", "PARECER", "RELATORIO", "DOC_FORNECEDOR", "OUTRO",
)
FONTES_PRECO = ("PAINEL_PRECOS", "CONTRATACAO_SIMILAR", "COTACAO_FORNECEDOR", "SITE", "OUTRO")
CLASSIFICACOES = ("PUBLIC", "INTERNAL", "CONFIDENTIAL", "RESTRICTED")
# Documento que o processo deveria ter a partir de cada etapa (Missing Documentation).
DOCUMENTOS_ESPERADOS = {
    "TERMO_REFERENCIA": ("ETP",),
    "PESQUISA_PRECOS": ("ETP", "TR"),
    "APROVACAO": ("ETP", "TR", "PESQUISA_PRECO"),
    "PUBLICADO": ("ETP", "TR", "PESQUISA_PRECO", "EDITAL"),
}
