"""convite vitrine

Revision ID: 2fba4a696c6c
Revises: 48afdc603fec
Create Date: 2026-08-04 16:39:23.367094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fba4a696c6c'
down_revision: Union[str, Sequence[str], None] = '48afdc603fec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('convite_vitrine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id_origem', sa.String(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('criado_por_usuario_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('validade_em', sa.DateTime(), nullable=True),
    sa.Column('tenant_id_gerado', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['criado_por_usuario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['tenant_id_gerado'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['tenant_id_origem'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_convite_vitrine_codigo'), 'convite_vitrine', ['codigo'], unique=True)
    op.create_index(op.f('ix_convite_vitrine_tenant_id_origem'), 'convite_vitrine', ['tenant_id_origem'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_convite_vitrine_tenant_id_origem'), table_name='convite_vitrine')
    op.drop_index(op.f('ix_convite_vitrine_codigo'), table_name='convite_vitrine')
    op.drop_table('convite_vitrine')
    # ### end Alembic commands ###
