"""schema inicial

Revision ID: 48afdc603fec
Revises: 
Create Date: 2026-08-03 16:55:11.359614

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48afdc603fec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('evento_tipo', sa.String(), nullable=False),
    sa.Column('entidade_tipo', sa.String(), nullable=False),
    sa.Column('entidade_id', sa.Integer(), nullable=False),
    sa.Column('ator_id', sa.String(), nullable=True),
    sa.Column('conta_id', sa.Integer(), nullable=True),
    sa.Column('canal', sa.String(), nullable=True),
    sa.Column('detalhes', sa.JSON(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_canal'), 'audit_log', ['canal'], unique=False)
    op.create_index(op.f('ix_audit_log_conta_id'), 'audit_log', ['conta_id'], unique=False)
    op.create_index(op.f('ix_audit_log_tenant_id'), 'audit_log', ['tenant_id'], unique=False)
    op.create_table('cnpj_estabelecimento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=False),
    sa.Column('razao_social', sa.String(), nullable=False),
    sa.Column('nome_fantasia', sa.String(), nullable=True),
    sa.Column('cnae_principal', sa.String(), nullable=False),
    sa.Column('porte', sa.String(), nullable=True),
    sa.Column('capital_social', sa.Float(), nullable=True),
    sa.Column('uf', sa.String(), nullable=False),
    sa.Column('municipio', sa.String(), nullable=True),
    sa.Column('situacao_cadastral', sa.String(), nullable=False),
    sa.Column('data_abertura', sa.String(), nullable=True),
    sa.Column('carregado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cnpj_estabelecimento_cnae_principal'), 'cnpj_estabelecimento', ['cnae_principal'], unique=False)
    op.create_index(op.f('ix_cnpj_estabelecimento_cnpj'), 'cnpj_estabelecimento', ['cnpj'], unique=True)
    op.create_index(op.f('ix_cnpj_estabelecimento_uf'), 'cnpj_estabelecimento', ['uf'], unique=False)
    op.create_table('cnpj_socio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cnpj_basico', sa.String(), nullable=False),
    sa.Column('nome_socio', sa.String(), nullable=False),
    sa.Column('qualificacao', sa.String(), nullable=False),
    sa.Column('carregado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cnpj_socio_cnpj_basico'), 'cnpj_socio', ['cnpj_basico'], unique=False)
    op.create_table('configuracao_canal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('canal', sa.String(), nullable=False),
    sa.Column('iniciado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'canal')
    )
    op.create_index(op.f('ix_configuracao_canal_tenant_id'), 'configuracao_canal', ['tenant_id'], unique=False)
    op.create_table('configuracao_comunicacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('tom', sa.String(), nullable=False),
    sa.Column('restricoes', sa.JSON(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracao_comunicacao_tenant_id'), 'configuracao_comunicacao', ['tenant_id'], unique=True)
    op.create_table('configuracao_envio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('remetente_nome', sa.String(), nullable=False),
    sa.Column('remetente_email', sa.String(), nullable=False),
    sa.Column('assinatura', sa.String(), nullable=False),
    sa.Column('horario_inicio', sa.Time(), nullable=False),
    sa.Column('horario_fim', sa.Time(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracao_envio_tenant_id'), 'configuracao_envio', ['tenant_id'], unique=True)
    op.create_table('configuracao_notificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('vendedor_id', sa.String(), nullable=False),
    sa.Column('vendedor_telefone', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracao_notificacao_tenant_id'), 'configuracao_notificacao', ['tenant_id'], unique=True)
    op.create_table('configuracao_nps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('dias_apos_reuniao_realizada', sa.Integer(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracao_nps_tenant_id'), 'configuracao_nps', ['tenant_id'], unique=True)
    op.create_table('configuracao_painel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('meta_mensal_reunioes', sa.Integer(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracao_painel_tenant_id'), 'configuracao_painel', ['tenant_id'], unique=True)
    op.create_table('configuracao_qualificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('limiar_padrao', sa.Float(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_configuracao_qualificacao_tenant_id'), 'configuracao_qualificacao', ['tenant_id'], unique=True)
    op.create_table('custo_aquisicao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('periodo', sa.String(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'periodo')
    )
    op.create_index(op.f('ix_custo_aquisicao_tenant_id'), 'custo_aquisicao', ['tenant_id'], unique=False)
    op.create_table('estagio_funil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_estagio_funil_tenant_id'), 'estagio_funil', ['tenant_id'], unique=False)
    op.create_table('faq_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('pergunta', sa.String(), nullable=False),
    sa.Column('resposta', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faq_item_tenant_id'), 'faq_item', ['tenant_id'], unique=False)
    op.create_table('icp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('grupo_id', sa.String(), nullable=False),
    sa.Column('clonado_de_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('segmento', sa.String(), nullable=False),
    sa.Column('porte', sa.String(), nullable=False),
    sa.Column('regiao', sa.String(), nullable=False),
    sa.Column('dores', sa.JSON(), nullable=False),
    sa.Column('gatilhos', sa.JSON(), nullable=False),
    sa.Column('cnae_codigos', sa.JSON(), nullable=False),
    sa.Column('ufs', sa.JSON(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['clonado_de_id'], ['icp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_icp_grupo_id'), 'icp', ['grupo_id'], unique=False)
    op.create_index(op.f('ix_icp_tenant_id'), 'icp', ['tenant_id'], unique=False)
    op.create_table('pausa_canal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('canal', sa.String(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('motivo', sa.String(), nullable=True),
    sa.Column('pausado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'canal')
    )
    op.create_index(op.f('ix_pausa_canal_tenant_id'), 'pausa_canal', ['tenant_id'], unique=False)
    op.create_table('plano',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('franquia_contas_mes', sa.Integer(), nullable=False),
    sa.Column('max_usuarios', sa.Integer(), nullable=False),
    sa.Column('preco_mensal', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('registro_envio_diario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('canal', sa.String(), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('quantidade_enviada', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'canal', 'data')
    )
    op.create_index(op.f('ix_registro_envio_diario_tenant_id'), 'registro_envio_diario', ['tenant_id'], unique=False)
    op.create_table('registro_reputacao_canal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('canal', sa.String(), nullable=False),
    sa.Column('data', sa.String(), nullable=False),
    sa.Column('enviados', sa.Integer(), nullable=False),
    sa.Column('bounces', sa.Integer(), nullable=False),
    sa.Column('spam_reports', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'canal', 'data')
    )
    op.create_index(op.f('ix_registro_reputacao_canal_tenant_id'), 'registro_reputacao_canal', ['tenant_id'], unique=False)
    op.create_table('registro_supressao_permanente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('identificador_hash', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registro_supressao_permanente_identificador_hash'), 'registro_supressao_permanente', ['identificador_hash'], unique=False)
    op.create_index(op.f('ix_registro_supressao_permanente_tenant_id'), 'registro_supressao_permanente', ['tenant_id'], unique=False)
    op.create_table('registro_tratamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo_tratamento', sa.String(), nullable=False),
    sa.Column('finalidade', sa.String(), nullable=False),
    sa.Column('base_legal', sa.String(), nullable=False),
    sa.Column('dados_tratados', sa.JSON(), nullable=False),
    sa.Column('balanceamento_documentado', sa.String(), nullable=False),
    sa.Column('versao', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_registro_tratamento_tipo_tratamento'), 'registro_tratamento', ['tipo_tratamento'], unique=False)
    op.create_table('regra_auto_aprovacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('habilitada', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'template_id')
    )
    op.create_index(op.f('ix_regra_auto_aprovacao_tenant_id'), 'regra_auto_aprovacao', ['tenant_id'], unique=False)
    op.create_table('template_whatsapp',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('corpo', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sincronizado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_whatsapp_tenant_id'), 'template_whatsapp', ['tenant_id'], unique=False)
    op.create_table('tenant',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('razao_social', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conexao_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id_origem', sa.String(), nullable=False),
    sa.Column('tenant_id_destino', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('respondida_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id_destino'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['tenant_id_origem'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id_origem', 'tenant_id_destino')
    )
    op.create_index(op.f('ix_conexao_empresa_tenant_id_destino'), 'conexao_empresa', ['tenant_id_destino'], unique=False)
    op.create_index(op.f('ix_conexao_empresa_tenant_id_origem'), 'conexao_empresa', ['tenant_id_origem'], unique=False)
    op.create_table('conta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('icp_id', sa.Integer(), nullable=False),
    sa.Column('cnpj', sa.String(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('dominio', sa.String(), nullable=True),
    sa.Column('porte', sa.String(), nullable=True),
    sa.Column('segmento', sa.String(), nullable=True),
    sa.Column('regiao', sa.String(), nullable=True),
    sa.Column('score_aderencia', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('motivo_descarte', sa.String(), nullable=True),
    sa.Column('origem', sa.String(), nullable=True),
    sa.Column('nps_classificacao', sa.String(), nullable=True),
    sa.Column('nps_nota', sa.Integer(), nullable=True),
    sa.Column('cliente_desde', sa.DateTime(), nullable=True),
    sa.Column('cliente_cancelado_em', sa.DateTime(), nullable=True),
    sa.Column('neo4j_node_id', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['icp_id'], ['icp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conta_cnpj'), 'conta', ['cnpj'], unique=False)
    op.create_index(op.f('ix_conta_tenant_id'), 'conta', ['tenant_id'], unique=False)
    op.create_table('licenca',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('plano_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('data_expiracao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plano_id'], ['plano.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_index(op.f('ix_licenca_tenant_id'), 'licenca', ['tenant_id'], unique=False)
    op.create_table('oferta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('icp_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('diferenciais', sa.JSON(), nullable=False),
    sa.Column('provas_sociais', sa.JSON(), nullable=False),
    sa.Column('faixa_preco_min', sa.Float(), nullable=True),
    sa.Column('faixa_preco_max', sa.Float(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['icp_id'], ['icp.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oferta_tenant_id'), 'oferta', ['tenant_id'], unique=False)
    op.create_table('perfil_empresa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('nome_exibicao', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('setor', sa.String(), nullable=True),
    sa.Column('site', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_index(op.f('ix_perfil_empresa_tenant_id'), 'perfil_empresa', ['tenant_id'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=True),
    sa.Column('google_sub', sa.String(), nullable=True),
    sa.Column('papel', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ultimo_login_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('google_sub')
    )
    op.create_index(op.f('ix_usuario_email'), 'usuario', ['email'], unique=True)
    op.create_index(op.f('ix_usuario_tenant_id'), 'usuario', ['tenant_id'], unique=False)
    op.create_table('cadencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('canais', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cadencia_tenant_id'), 'cadencia', ['tenant_id'], unique=False)
    op.create_table('campo_enriquecido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('campo', sa.String(), nullable=False),
    sa.Column('valor', sa.String(), nullable=False),
    sa.Column('fonte', sa.String(), nullable=False),
    sa.Column('coletado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conta_franquia_consumo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('ano_mes', sa.String(), nullable=False),
    sa.Column('consumido_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'conta_id', 'ano_mes')
    )
    op.create_index(op.f('ix_conta_franquia_consumo_tenant_id'), 'conta_franquia_consumo', ['tenant_id'], unique=False)
    op.create_table('convite_cadastro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('papel_concedido', sa.String(), nullable=False),
    sa.Column('criado_por_usuario_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('validade_em', sa.DateTime(), nullable=True),
    sa.Column('usado_por_usuario_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['criado_por_usuario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['usado_por_usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_convite_cadastro_codigo'), 'convite_cadastro', ['codigo'], unique=True)
    op.create_index(op.f('ix_convite_cadastro_tenant_id'), 'convite_cadastro', ['tenant_id'], unique=False)
    op.create_table('decisor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cargo', sa.String(), nullable=True),
    sa.Column('canal_provavel', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('neo4j_node_id', sa.String(), nullable=True),
    sa.Column('ultima_interacao_em', sa.DateTime(), nullable=True),
    sa.Column('suprimido_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisor_tenant_id'), 'decisor', ['tenant_id'], unique=False)
    op.create_table('descarte_conta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(), nullable=False),
    sa.Column('cnae', sa.String(), nullable=True),
    sa.Column('porte', sa.String(), nullable=True),
    sa.Column('uf', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_descarte_conta_tenant_id'), 'descarte_conta', ['tenant_id'], unique=False)
    op.create_table('interacao_tenant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.Column('criado_por_usuario_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['criado_por_usuario_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interacao_tenant_tenant_id'), 'interacao_tenant', ['tenant_id'], unique=False)
    op.create_table('material_oferta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('oferta_id', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(), nullable=False),
    sa.Column('tipo_mime', sa.String(), nullable=False),
    sa.Column('caminho', sa.String(), nullable=False),
    sa.Column('tamanho_bytes', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['oferta_id'], ['oferta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_oferta_tenant_id'), 'material_oferta', ['tenant_id'], unique=False)
    op.create_table('mensagem_rede_social',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id_remetente', sa.String(), nullable=False),
    sa.Column('tenant_id_destinatario', sa.String(), nullable=False),
    sa.Column('usuario_remetente_id', sa.Integer(), nullable=True),
    sa.Column('texto', sa.String(), nullable=False),
    sa.Column('lida_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id_destinatario'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['tenant_id_remetente'], ['tenant.id'], ),
    sa.ForeignKeyConstraint(['usuario_remetente_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensagem_rede_social_tenant_id_destinatario'), 'mensagem_rede_social', ['tenant_id_destinatario'], unique=False)
    op.create_index(op.f('ix_mensagem_rede_social_tenant_id_remetente'), 'mensagem_rede_social', ['tenant_id_remetente'], unique=False)
    op.create_table('negocio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('vendedor_usuario_id', sa.Integer(), nullable=True),
    sa.Column('estagio_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('probabilidade', sa.Integer(), nullable=False),
    sa.Column('origem', sa.String(), nullable=False),
    sa.Column('ganho_em', sa.DateTime(), nullable=True),
    sa.Column('perdido_em', sa.DateTime(), nullable=True),
    sa.Column('motivo_perda', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], ),
    sa.ForeignKeyConstraint(['estagio_id'], ['estagio_funil.id'], ),
    sa.ForeignKeyConstraint(['vendedor_usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negocio_tenant_id'), 'negocio', ['tenant_id'], unique=False)
    op.create_table('atividade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('negocio_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['negocio_id'], ['negocio.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_atividade_negocio_id'), 'atividade', ['negocio_id'], unique=False)
    op.create_index(op.f('ix_atividade_tenant_id'), 'atividade', ['tenant_id'], unique=False)
    op.create_table('conversa_qualificacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('decisor_id', sa.Integer(), nullable=False),
    sa.Column('canal', sa.String(), nullable=False),
    sa.Column('etapa_atual', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('motivo_devolucao', sa.String(), nullable=True),
    sa.Column('transferido_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], ),
    sa.ForeignKeyConstraint(['decisor_id'], ['decisor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversa_qualificacao_tenant_id'), 'conversa_qualificacao', ['tenant_id'], unique=False)
    op.create_table('indicacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('promotor_decisor_id', sa.Integer(), nullable=False),
    sa.Column('promotor_conta_id', sa.Integer(), nullable=False),
    sa.Column('codigo_indicacao', sa.String(), nullable=False),
    sa.Column('canal', sa.String(), nullable=False),
    sa.Column('indicado_nome', sa.String(), nullable=True),
    sa.Column('indicado_identificador', sa.String(), nullable=True),
    sa.Column('intra_rede', sa.Boolean(), nullable=False),
    sa.Column('conta_gerada_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('convertida_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conta_gerada_id'], ['conta.id'], ),
    sa.ForeignKeyConstraint(['promotor_conta_id'], ['conta.id'], ),
    sa.ForeignKeyConstraint(['promotor_decisor_id'], ['decisor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicacao_codigo_indicacao'), 'indicacao', ['codigo_indicacao'], unique=True)
    op.create_index(op.f('ix_indicacao_tenant_id'), 'indicacao', ['tenant_id'], unique=False)
    op.create_table('pesquisa_nps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('decisor_id', sa.Integer(), nullable=False),
    sa.Column('marco', sa.String(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=True),
    sa.Column('classificacao', sa.String(), nullable=True),
    sa.Column('enviada_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('respondida_em', sa.DateTime(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], ),
    sa.ForeignKeyConstraint(['decisor_id'], ['decisor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pesquisa_nps_tenant_id'), 'pesquisa_nps', ['tenant_id'], unique=False)
    op.create_table('reuniao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('decisor_id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.String(), nullable=False),
    sa.Column('data_hora', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('origem_crm_id', sa.String(), nullable=True),
    sa.Column('horarios_propostos', sa.JSON(), nullable=False),
    sa.Column('horario_confirmado', sa.DateTime(), nullable=True),
    sa.Column('link_reuniao', sa.String(), nullable=True),
    sa.Column('origem_calendario_id', sa.String(), nullable=True),
    sa.Column('reagendado_de_id', sa.Integer(), nullable=True),
    sa.Column('lembrete_d1_enviado_em', sa.DateTime(), nullable=True),
    sa.Column('lembrete_h2_enviado_em', sa.DateTime(), nullable=True),
    sa.Column('qualificada_confirmada', sa.Boolean(), nullable=True),
    sa.Column('motivo_qualificacao', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], ),
    sa.ForeignKeyConstraint(['decisor_id'], ['decisor.id'], ),
    sa.ForeignKeyConstraint(['reagendado_de_id'], ['reuniao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reuniao_tenant_id'), 'reuniao', ['tenant_id'], unique=False)
    op.create_table('toque_cadencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('cadencia_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('canal', sa.String(), nullable=False),
    sa.Column('intervalo_dias_apos_anterior', sa.Integer(), nullable=False),
    sa.Column('template_whatsapp_id', sa.String(), nullable=True),
    sa.Column('ab_teste_habilitado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cadencia_id'], ['cadencia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_toque_cadencia_tenant_id'), 'toque_cadencia', ['tenant_id'], unique=False)
    op.create_table('alerta_detrator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('pesquisa_nps_id', sa.Integer(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('decisor_id', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Integer(), nullable=False),
    sa.Column('sugestao_acao', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], ),
    sa.ForeignKeyConstraint(['decisor_id'], ['decisor.id'], ),
    sa.ForeignKeyConstraint(['pesquisa_nps_id'], ['pesquisa_nps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerta_detrator_tenant_id'), 'alerta_detrator', ['tenant_id'], unique=False)
    op.create_table('mensagem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('cadencia_id', sa.Integer(), nullable=True),
    sa.Column('decisor_id', sa.Integer(), nullable=False),
    sa.Column('toque_cadencia_id', sa.Integer(), nullable=True),
    sa.Column('canal', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('conteudo', sa.String(), nullable=False),
    sa.Column('variante_ab', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('agendado_para', sa.DateTime(), nullable=True),
    sa.Column('enviado_em', sa.DateTime(), nullable=True),
    sa.Column('motivo_falha', sa.String(), nullable=True),
    sa.Column('tentativas_envio', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['cadencia_id'], ['cadencia.id'], ),
    sa.ForeignKeyConstraint(['decisor_id'], ['decisor.id'], ),
    sa.ForeignKeyConstraint(['toque_cadencia_id'], ['toque_cadencia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensagem_tenant_id'), 'mensagem', ['tenant_id'], unique=False)
    op.create_table('notificacao_vendedor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('conversa_id', sa.Integer(), nullable=False),
    sa.Column('vendedor_id', sa.String(), nullable=False),
    sa.Column('resumo', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('primeiro_contato_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversa_id'], ['conversa_qualificacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notificacao_vendedor_tenant_id'), 'notificacao_vendedor', ['tenant_id'], unique=False)
    op.create_table('qualificacao_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('conta_id', sa.Integer(), nullable=False),
    sa.Column('decisor_id', sa.Integer(), nullable=False),
    sa.Column('conversa_id', sa.Integer(), nullable=True),
    sa.Column('score_total', sa.Float(), nullable=False),
    sa.Column('criterios', sa.JSON(), nullable=False),
    sa.Column('limiar_configurado', sa.Float(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conta_id'], ['conta.id'], ),
    sa.ForeignKeyConstraint(['conversa_id'], ['conversa_qualificacao.id'], ),
    sa.ForeignKeyConstraint(['decisor_id'], ['decisor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qualificacao_score_tenant_id'), 'qualificacao_score', ['tenant_id'], unique=False)
    op.create_table('turno_conversa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('conversa_id', sa.Integer(), nullable=False),
    sa.Column('direcao', sa.String(), nullable=False),
    sa.Column('conteudo', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['conversa_id'], ['conversa_qualificacao.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_turno_conversa_tenant_id'), 'turno_conversa', ['tenant_id'], unique=False)
    op.create_table('aprovacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('mensagem_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('aprovador_id', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('decidido_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['mensagem_id'], ['mensagem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aprovacao_tenant_id'), 'aprovacao', ['tenant_id'], unique=False)
    op.create_table('tarefa_linkedin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('mensagem_id', sa.Integer(), nullable=False),
    sa.Column('decisor_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(), nullable=False),
    sa.Column('link_perfil', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['decisor_id'], ['decisor.id'], ),
    sa.ForeignKeyConstraint(['mensagem_id'], ['mensagem.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tarefa_linkedin_tenant_id'), 'tarefa_linkedin', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tarefa_linkedin_tenant_id'), table_name='tarefa_linkedin')
    op.drop_table('tarefa_linkedin')
    op.drop_index(op.f('ix_aprovacao_tenant_id'), table_name='aprovacao')
    op.drop_table('aprovacao')
    op.drop_index(op.f('ix_turno_conversa_tenant_id'), table_name='turno_conversa')
    op.drop_table('turno_conversa')
    op.drop_index(op.f('ix_qualificacao_score_tenant_id'), table_name='qualificacao_score')
    op.drop_table('qualificacao_score')
    op.drop_index(op.f('ix_notificacao_vendedor_tenant_id'), table_name='notificacao_vendedor')
    op.drop_table('notificacao_vendedor')
    op.drop_index(op.f('ix_mensagem_tenant_id'), table_name='mensagem')
    op.drop_table('mensagem')
    op.drop_index(op.f('ix_alerta_detrator_tenant_id'), table_name='alerta_detrator')
    op.drop_table('alerta_detrator')
    op.drop_index(op.f('ix_toque_cadencia_tenant_id'), table_name='toque_cadencia')
    op.drop_table('toque_cadencia')
    op.drop_index(op.f('ix_reuniao_tenant_id'), table_name='reuniao')
    op.drop_table('reuniao')
    op.drop_index(op.f('ix_pesquisa_nps_tenant_id'), table_name='pesquisa_nps')
    op.drop_table('pesquisa_nps')
    op.drop_index(op.f('ix_indicacao_tenant_id'), table_name='indicacao')
    op.drop_index(op.f('ix_indicacao_codigo_indicacao'), table_name='indicacao')
    op.drop_table('indicacao')
    op.drop_index(op.f('ix_conversa_qualificacao_tenant_id'), table_name='conversa_qualificacao')
    op.drop_table('conversa_qualificacao')
    op.drop_index(op.f('ix_atividade_tenant_id'), table_name='atividade')
    op.drop_index(op.f('ix_atividade_negocio_id'), table_name='atividade')
    op.drop_table('atividade')
    op.drop_index(op.f('ix_negocio_tenant_id'), table_name='negocio')
    op.drop_table('negocio')
    op.drop_index(op.f('ix_mensagem_rede_social_tenant_id_remetente'), table_name='mensagem_rede_social')
    op.drop_index(op.f('ix_mensagem_rede_social_tenant_id_destinatario'), table_name='mensagem_rede_social')
    op.drop_table('mensagem_rede_social')
    op.drop_index(op.f('ix_material_oferta_tenant_id'), table_name='material_oferta')
    op.drop_table('material_oferta')
    op.drop_index(op.f('ix_interacao_tenant_tenant_id'), table_name='interacao_tenant')
    op.drop_table('interacao_tenant')
    op.drop_index(op.f('ix_descarte_conta_tenant_id'), table_name='descarte_conta')
    op.drop_table('descarte_conta')
    op.drop_index(op.f('ix_decisor_tenant_id'), table_name='decisor')
    op.drop_table('decisor')
    op.drop_index(op.f('ix_convite_cadastro_tenant_id'), table_name='convite_cadastro')
    op.drop_index(op.f('ix_convite_cadastro_codigo'), table_name='convite_cadastro')
    op.drop_table('convite_cadastro')
    op.drop_index(op.f('ix_conta_franquia_consumo_tenant_id'), table_name='conta_franquia_consumo')
    op.drop_table('conta_franquia_consumo')
    op.drop_table('campo_enriquecido')
    op.drop_index(op.f('ix_cadencia_tenant_id'), table_name='cadencia')
    op.drop_table('cadencia')
    op.drop_index(op.f('ix_usuario_tenant_id'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_email'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_perfil_empresa_tenant_id'), table_name='perfil_empresa')
    op.drop_table('perfil_empresa')
    op.drop_index(op.f('ix_oferta_tenant_id'), table_name='oferta')
    op.drop_table('oferta')
    op.drop_index(op.f('ix_licenca_tenant_id'), table_name='licenca')
    op.drop_table('licenca')
    op.drop_index(op.f('ix_conta_tenant_id'), table_name='conta')
    op.drop_index(op.f('ix_conta_cnpj'), table_name='conta')
    op.drop_table('conta')
    op.drop_index(op.f('ix_conexao_empresa_tenant_id_origem'), table_name='conexao_empresa')
    op.drop_index(op.f('ix_conexao_empresa_tenant_id_destino'), table_name='conexao_empresa')
    op.drop_table('conexao_empresa')
    op.drop_table('tenant')
    op.drop_index(op.f('ix_template_whatsapp_tenant_id'), table_name='template_whatsapp')
    op.drop_table('template_whatsapp')
    op.drop_index(op.f('ix_regra_auto_aprovacao_tenant_id'), table_name='regra_auto_aprovacao')
    op.drop_table('regra_auto_aprovacao')
    op.drop_index(op.f('ix_registro_tratamento_tipo_tratamento'), table_name='registro_tratamento')
    op.drop_table('registro_tratamento')
    op.drop_index(op.f('ix_registro_supressao_permanente_tenant_id'), table_name='registro_supressao_permanente')
    op.drop_index(op.f('ix_registro_supressao_permanente_identificador_hash'), table_name='registro_supressao_permanente')
    op.drop_table('registro_supressao_permanente')
    op.drop_index(op.f('ix_registro_reputacao_canal_tenant_id'), table_name='registro_reputacao_canal')
    op.drop_table('registro_reputacao_canal')
    op.drop_index(op.f('ix_registro_envio_diario_tenant_id'), table_name='registro_envio_diario')
    op.drop_table('registro_envio_diario')
    op.drop_table('plano')
    op.drop_index(op.f('ix_pausa_canal_tenant_id'), table_name='pausa_canal')
    op.drop_table('pausa_canal')
    op.drop_index(op.f('ix_icp_tenant_id'), table_name='icp')
    op.drop_index(op.f('ix_icp_grupo_id'), table_name='icp')
    op.drop_table('icp')
    op.drop_index(op.f('ix_faq_item_tenant_id'), table_name='faq_item')
    op.drop_table('faq_item')
    op.drop_index(op.f('ix_estagio_funil_tenant_id'), table_name='estagio_funil')
    op.drop_table('estagio_funil')
    op.drop_index(op.f('ix_custo_aquisicao_tenant_id'), table_name='custo_aquisicao')
    op.drop_table('custo_aquisicao')
    op.drop_index(op.f('ix_configuracao_qualificacao_tenant_id'), table_name='configuracao_qualificacao')
    op.drop_table('configuracao_qualificacao')
    op.drop_index(op.f('ix_configuracao_painel_tenant_id'), table_name='configuracao_painel')
    op.drop_table('configuracao_painel')
    op.drop_index(op.f('ix_configuracao_nps_tenant_id'), table_name='configuracao_nps')
    op.drop_table('configuracao_nps')
    op.drop_index(op.f('ix_configuracao_notificacao_tenant_id'), table_name='configuracao_notificacao')
    op.drop_table('configuracao_notificacao')
    op.drop_index(op.f('ix_configuracao_envio_tenant_id'), table_name='configuracao_envio')
    op.drop_table('configuracao_envio')
    op.drop_index(op.f('ix_configuracao_comunicacao_tenant_id'), table_name='configuracao_comunicacao')
    op.drop_table('configuracao_comunicacao')
    op.drop_index(op.f('ix_configuracao_canal_tenant_id'), table_name='configuracao_canal')
    op.drop_table('configuracao_canal')
    op.drop_index(op.f('ix_cnpj_socio_cnpj_basico'), table_name='cnpj_socio')
    op.drop_table('cnpj_socio')
    op.drop_index(op.f('ix_cnpj_estabelecimento_uf'), table_name='cnpj_estabelecimento')
    op.drop_index(op.f('ix_cnpj_estabelecimento_cnpj'), table_name='cnpj_estabelecimento')
    op.drop_index(op.f('ix_cnpj_estabelecimento_cnae_principal'), table_name='cnpj_estabelecimento')
    op.drop_table('cnpj_estabelecimento')
    op.drop_index(op.f('ix_audit_log_tenant_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_conta_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_canal'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
