"""abertura de email

Revision ID: 741eed234a25
Revises: 2fba4a696c6c
Create Date: 2026-08-05 10:56:27.280998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '741eed234a25'
down_revision: Union[str, Sequence[str], None] = '2fba4a696c6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mensagem', sa.Column('aberto_em', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mensagem', 'aberto_em')
    # ### end Alembic commands ###
